name: hyper_local_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # 🚀 [NEW] 앱 아이콘과 로딩 화면을 만들어줄 마법의 도구 추가!
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.4.0"

flutter:
  uses-material-design: true
  assets:
    - assets/lightning_icon.png
    - assets/app_logo.png # 🚀 [NEW] 준비하신 새 로고 이미지 경로 추가!

# 🚀 [NEW] 여기서부터 파일 맨 아래까지가 아이콘 & 스플래시 생성 설정입니다.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/app_logo.png"
  fullscreen: true