// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPVzMUqW7GmSDLVxQmvRlRTK3jJqvqgMA',
    appId: '1:642891163198:web:ed8dcbbd4c473e3a73536f',
    messagingSenderId: '642891163198',
    projectId: 'hyper-local-project',
    authDomain: 'hyper-local-project.firebaseapp.com',
    storageBucket: 'hyper-local-project.firebasestorage.app',
    measurementId: 'G-RCPH1KEVL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1az9QYQru0gO0ZQRptrIWbCJPwuhtfM',
    appId: '1:642891163198:android:9f9aa1566942316273536f',
    messagingSenderId: '642891163198',
    projectId: 'hyper-local-project',
    storageBucket: 'hyper-local-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASU1waKXGKpAB3HIvqDn9L7nSGknGaXNw',
    appId: '1:642891163198:ios:26dac023e4bb737d73536f',
    messagingSenderId: '642891163198',
    projectId: 'hyper-local-project',
    storageBucket: 'hyper-local-project.firebasestorage.app',
    iosBundleId: 'com.example.hyperLocalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASU1waKXGKpAB3HIvqDn9L7nSGknGaXNw',
    appId: '1:642891163198:ios:26dac023e4bb737d73536f',
    messagingSenderId: '642891163198',
    projectId: 'hyper-local-project',
    storageBucket: 'hyper-local-project.firebasestorage.app',
    iosBundleId: 'com.example.hyperLocalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPVzMUqW7GmSDLVxQmvRlRTK3jJqvqgMA',
    appId: '1:642891163198:web:d8416eb6c176321273536f',
    messagingSenderId: '642891163198',
    projectId: 'hyper-local-project',
    authDomain: 'hyper-local-project.firebaseapp.com',
    storageBucket: 'hyper-local-project.firebasestorage.app',
    measurementId: 'G-56ZFBL889Q',
  );
}
